apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
{{ (.Files.Glob "ioc-config/{liveness.sh,stop.sh}").AsConfig | indent 2 }}
  start.sh: |
    {{- tpl (.Files.Get "ioc-config/start.sh") . | nindent 4 }}
  fastcs.yaml: |
    {{- tpl (.Files.Get "ioc-config/fastcs.yaml") . | nindent 4 }}