{{- $enabled := eq .Values.global.enabled false | ternary false true -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Values.detectorName }}-eiger-fan
  labels:
    enabled: {{ $enabled | quote }}
spec:
  replicas: {{ $enabled | ternary 1 0 }}
  selector:
    matchLabels:
      app: {{ .Values.detectorName }}-eiger-fan
  template:
    metadata:
      labels:
        app: {{ .Values.detectorName }}-eiger-fan
    spec:
      volumes:
        - name: {{ $.Values.detectorName }}-odin-config-volume
          configMap:
            name: {{ $.Values.detectorName }}-odin-config
            defaultMode: 0755
      containers:
        - name: {{ .Values.detectorName }}-eiger-fan
          image: {{ .Values.image }}
          command:
            - /odin/deployment/eiger-fan.sh
          ports:
            - containerPort: 5559
          resources:
            limits:
              memory: "256Mi" # TODO: Increase when running on EPU
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: {{ $.Values.detectorName }}-odin-config-volume
              mountPath: /odin/deployment
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.detectorName }}-eiger-fan
spec:
  selector:
    app: {{ .Values.detectorName }}-eiger-fan
  ports:
    - name: {{ .Values.detectorName }}-eiger-fan-ctrl
      protocol: TCP
      port: 5559
{{- range $idx, $e := until (int $.Values.odinDataCount) }}
    - name: {{ $.Values.detectorName }}-eiger-fan-data-{{ $idx }}
      protocol: TCP
      port: 3160{{ $idx }}
{{- end }}
