controllers:
  - id: {{ .Values.pvPrefix }}
    type: fastcs_eiger.EigerOdinController
    connection_settings:
      ip: "{{ .Values.detectorIp }}"
      port: 80
    odin_connection_settings:
      ip: "{{ .Values.detectorName }}-odin-server"
      port: 8888
    api_version: "1.8.0"
transport:
  - epicsca:
{{- if .Values.aliases }}
      aliases:
{{ .Values.aliases | toYaml | indent 8 }}
{{- end }}
    gui:
      title: Eiger
      output_dir: /epics/opi/
