{{- $enabled := eq .Values.global.enabled false | ternary false true -}}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ .Values.detectorName }}-meta-writer
  labels:
    enabled: {{ $enabled | quote }}
spec:
  replicas: {{ $enabled | ternary 1 0 }}
  selector:
    matchLabels:
      app: {{ .Values.detectorName }}-meta-writer
  template:
    metadata:
      labels:
        app: {{ .Values.detectorName }}-meta-writer
    spec:
      volumes:
        - name: {{ $.Values.detectorName }}-odin-config-volume
          configMap:
            name: {{ $.Values.detectorName }}-odin-config
            defaultMode: 0755
      containers:
        - name: {{ .Values.detectorName }}-meta-writer
          image: {{ .Values.image }}
          command:
            - /odin/deployment/meta-writer.sh
          ports:
            - containerPort: 5659
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "500m"
          volumeMounts:
            - name: {{ $.Values.detectorName }}-odin-config-volume
              mountPath: /odin/deployment
          env:
            - name: OPENSSL_FORCE_FIPS_MODE
              value: "0"
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.detectorName }}-meta-writer
spec:
  selector:
    app: {{ .Values.detectorName }}-meta-writer
  ports:
    - name: {{ .Values.detectorName }}-meta-writer-ctrl
      protocol: TCP
      port: 5659
