name: Build and push helm charts

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

env:
  HELM_VERSION_TO_INSTALL: 3.14.3

jobs:
  build-and-push-helm-charts:
    name: Build and push helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install helm
        uses: Azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: Package helm charts
        run: |
          set -x

          if [ "${GITHUB_REF_TYPE}" == "tag" ] ; then
            VERSION=${GITHUB_REF_NAME}
          else
            VERSION="0.0.0-b0"
          fi

          for chart in Charts/*; do
            (
              cd $(realpath $chart)
              helm package -u --app-version ${VERSION} --version ${VERSION} .
            )
          done

      - name: Push helm charts to registry
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        run: |
          set -x

          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin
          REGISTRY=oci://ghcr.io/diamondlightsource

          for chart in Charts/*; do
            (
              cd $(realpath $chart)
              NAME=$(sed -n '/^name: */s///p' Chart.yaml)
              PACKAGE=${NAME}-${GITHUB_REF_NAME}.tgz

              helm push "$PACKAGE" $REGISTRY
            )
          done
